# Generated by Django 4.2.3 on 2023-07-23 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_alter_contact_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='first_name',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=60)),
                ('interaction_type', models.CharField(blank=True, choices=[('email', 'Email'), ('call', 'Phone call'), ('text', 'Text message'), ('meeting_in_person', 'In person meeting'), ('meeting_virtual', 'Virtual meeting'), ('other', 'Other')], max_length=50, null=True)),
                ('interaction_date', models.DateTimeField(blank=True, null=True)),
                ('interaction_location', models.CharField(blank=True, max_length=50, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='contacts.contact')),
            ],
        ),
    ]
